import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const dynamic = 'force-dynamic';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <div className="flex-1 w-full">
          {children}
        </div>

        {/* Globaler Demo-Pflicht-Hinweis */}
        <footer className="w-full bg-slate-900 border-t border-slate-800 text-slate-400 text-center py-4 px-4 text-xs z-[9999] mt-auto relative">
          <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-center gap-2">
            <span>⚠️ <strong>Wichtiger Hinweis:</strong> Dies ist ein Portfolio-Projekt und eine reine Demo-Website.</span>
            <span>Alle Marken, Fahrzeuge, Produkte, Unternehmen und Angebote sind vollständig fiktiv.</span>
          </div>
        </footer>
      </body>
    </html>
  );
}
