name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and Create Env
        run: |
          # Wir mappen hier BASIC_AUTH (GitHub) auf ADMIN (dein Code)
          echo "ADMIN_USER=${{ secrets.BASIC_AUTH_USER }}" >> .env.production
          echo "ADMIN_PASSWORD=${{ secrets.BASIC_AUTH_PASSWORD }}" >> .env.production
          npm run build
        env:
          ADMIN_USER: ${{ secrets.BASIC_AUTH_USER }}
          ADMIN_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEBENTWICKLER_DEMO }}
          channelId: live
          projectId: webentwickler-demo
          force: true
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          ADMIN_USER: ${{ secrets.BASIC_AUTH_USER }}
          ADMIN_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}